const server = `http://localhost:4000`
const api = {
    server: server,
    login: `${server}/auth/login`,
    signup: `${server}/auth/register`,
    logout: ``,
    user: (id) => `${server}/users/${id}`,
    student: (id) => `${server}/students/${id}`,
    deleteMe: `${server}/users/delete/me`,
    delteUser: (id) => `${server}/users/deletebyid/${id}`,
    editProfile: (username) => `${server}/users/${username}/edit`,
    addAdmin: (id) => `${server}/auth/addadmin/${id}`,
    instructor: (id) => `${server}/instructors/${id}`,
    addInstructor: `${server}/instructors/newInstructor`,
    deleteInstructor: (id) => `${server}/instructors/delete/${id}`,
    deleteAllInstrunctors: `${server}/instructors/delete_all`,
    getStudents: `${server}/students`,
    getAdmins: `${server}/users/admins/getadmins`,
    getInstructors: `${server}/instructors`,
    getTopics: `${server}/topics`,
    editTopic: (id) => `${server}/topics/editTopic/${id}`,
    addTopic: `${server}/topics/newTopic`,
    getArticle: (id) => `${server}/articles/getbyarticleid/${id}`,
    getArticleTopics: (id) => `${server}/articles/getarticletopics/${id}`,
    getArticles: `${server}/articles`,
    addArticle: `${server}/articles/create`,
    getInstructorArticles: (id) => `${server}/articles/getinstructorarticles/${id}`,
    addArticleTopics: (id) => `${server}/articles/editarticletopics/${id}`,
    editArticleTopics: (id) => `${server}/articles/editarticletopics/${id}`,
    editArticle: (id) => `${server}/articles/edit/${id}`,
    deleteArticle: (id) => `${server}/articles/${id}`,
    userReadArticle: (id) => `${server}/articles/readarticle/${id}`,
    userLikeArticle: (id) => `${server}/articles/likearticle/${id}`,
    getArticlComments: (id) => `${server}/comments/articles/${id}`,
    addArticlComments: (id) => `${server}/comments/create/${id}`,//article_id
    editeComment: (id) => `${server}/comments/edit/${id}`,//comment_id
    deleteComment: (id) => `${server}/comments/${id}`,//comment_id
    getCourse: (id) => `${server}/courses/${id}`,
    getAllCourses: `${server}/courses/`,
    getCoursesOfStudent: (s_id) => `${server}/courses/getcoursesofstudent/${s_id}`,
    addCourse: `${server}/courses/create`,
    deleteCourse: (id) => `${server}/courses/${id}`,
    editCourse: (id) => `${server}/courses/${id}`,
    enrollCourse: (id) => `${server}/courses/enroll/${id}`,
    disenrollCourse: (id) => `${server}/courses/disenroll/${id}`,
    editReview: (c_id, u_id) => `${server}/courses/review/edit/${c_id}/${u_id}`,
    deleteReview: (c_id, u_id) => `${server}/courses/deleteonereview/${c_id}/${u_id}`,
    deleteAllReviews: (c_id) => `${server}/courses/deletecoursereviews/${c_id}`, //admin
    getInstructorCourses: (i_id) => `${server}/courses/instructors/${i_id}`,
    getInstructorQuizzes: (i_id) => `${server}/quizzes/getByInstructor/${i_id}`,
    getInstructorQuestions: `${server}/questions/getByInstructor/`,
    addLesson: `${server}/lessons/newlesson`,
    editLesson: (l_id) => `${server}/lessons/editlesson/${l_id}`,
    deleteLesson: (l_id) => `${server}/lessons/deletelessonbyid/${l_id}`,
    getCourseLessons: (c_id) => `${server}/lessons/getlessonsbycourse/${c_id}`,
    getLesson: (l_id) => `${server}/lessons/getlessonbyid/${l_id}`,
    getDiscussion: (c_id) => `${server}/discussions/getcoursediscussion/${c_id}`,

    addQuestion: `${server}/questions/create`,
    addQuiz: `${server}/quizzes/create`,
    getStudentQuizzes: (s_id) => `${server}/quizzes/getByStudent/${s_id}`,
    takeQuiz: (q_id) => `${server}/quizzes/take/${q_id}`,
    getQuizById: (q_id) => `${server}/quizzes/getquizbyid/${q_id}`,
    getAllQuizzes: `${server}/quizzes/`,
}
export default api